alias gti="git"
alias tmuxls="tmux list-sessions"
alias tmuxa="tmux attach -t "
alias reload="source $HOME/.bashrc"
alias ..="cd .."
alias ...="cd ../.."
alias ll="ls -l"
alias la="ls -a"
alias cdp="cd /mnt/c/Users/vromero/projects"
alias cdv="cd /mnt/c/Users/vromero/projects/vodafone"
alias dotfiles="cd ~/.dotfiles"
alias vf1="ssh -i /home/vromero/.ssh/vf_privada_1a.pem ec2-user@vf_host1"
alias vf2="ssh -i /home/vromero/.ssh/vf_privada_1a.pem ec2-user@vf_host2"
alias vf3="ssh -i /home/vromero/.ssh/vf_privada_1a.pem ec2-user@vf_host3"
alias vf4="ssh -i /home/vromero/.ssh/vf_privada_1a.pem ec2-user@vf_host4"
alias vf5="ssh -i /home/vromero/.ssh/vf_privada_1a.pem ec2-user@vf_host5"
alias vf6="ssh -i /home/vromero/.ssh/vf_privada_1a.pem ec2-user@vf_host6"
alias vf7="ssh -i /home/vromero/.ssh/vf_privada_1a.pem ec2-user@vf_host7"
alias vf8="ssh -i /home/vromero/.ssh/vf_privada_1a.pem ec2-user@vf_host8"

alias pimegen="mvn archetype:generate -DarchetypeCatalog=local"

alias w2a="/mnt/c/Users/vromero/projects/python-avro-generator/wsdl2avro.py"
alias codegen="/mnt/c/Users/vromero/projects/vodafone/producer-code-generator/generator.py"
