alias tmuxls="tmux list-sessions"
alias tmuxa="tmux attach -t "
alias reload="source $HOME/.bashrc"
alias ..="cd .."
alias ...="cd ../.."
alias ll="ls -l"
alias la="ls -a"
alias cdp="cd $HOME/projects"
alias dotfiles="cd ~/.dotfiles"

